modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"

[[mods]]
    modId="jepp"
    version="${file.jarVersion}"
    displayName="Just Enough Painting Previews"
    logoFile="icon.png"
    credits="MehVahdJukaar"
    authors="MehVahdJukaar"
    itemIcon="minecraft:painting"
    description="A JEI plugin that displays all the available paintings in its own handy window"

[[dependencies.jepp]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.jepp]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.jepp]]
    modId="jei"
    mandatory=true
    versionRange="[11.0.0.200,)"
    ordering="NONE"
    side="CLIENT"
